### ISSUE TITLE
which tensorflow version should i use?

### ISSUE THREAD

**Issue by bellgrylls** [JeremyCJM/CCST#2]
hi,I`m interested in your work.Recently i run the code.But it need tensorflow.So i`m wondering which version should i install.

**Comment by JeremyCJM** [comment]
Hi, thanks for your interest. The latest TensorFlow should work fine. The TensorFlow should be only for the tensorboard logs.

**Comment by bellgrylls** [comment]
ok,thanks for your kindly answer.
