### ISSUE TITLE
Why testing during training

### ISSUE THREAD

**Issue by ZhenyuLiu-SYSU** [JeremyCJM/CCST#4]
Dear author：

I'm glad to see your excellent work. 
As I'm a newcomer to the DG field, I would like to ask why this piece of testing code was added to the training process.
I would appreciate it if you could reply！
![image](https://user-images.githubusercontent.com/74093654/226922636-739c3751-9f34-4cc9-95a0-6709d8b3eae7.png)

**Comment by JeremyCJM** [comment]
We follow the same setting as [official Jigen paper code](https://github.com/fmcarlucci/JigenDG) for a fair comparison. This is to test the model generalization performance on the target domain at each training epoch, which does not influence the training process.

**Comment by ZhenyuLiu-BJFU** [comment]
> 

I understand.
Thank you!
