### ISSUE TITLE
Request for Model Weights(vgg and decoder) from Your WACV 2023 Paper

### ISSUE THREAD

**Issue by Kevin7720** [JeremyCJM/CCST#6]
If possible, could you please share the model weights directly? I have observed that the GitHub link to the weights is currently inactive. 

Download [decoder.pth](https://drive.google.com/file/d/1bMfhMMwPeXnYSQI6cDWElSZxOxc6aVyr/view?usp=sharing) / [vgg_normalized.pth](https://drive.google.com/file/d/1EpkBA2K2eYILDSyPTt0fztz59UjAIpZU/view?usp=sharing) and put them under `./style_transfer/AdaIN/models/`.

**Comment by JeremyCJM** [comment]
Here is the download link: https://github.com/naoto0804/pytorch-AdaIN/releases/tag/v0.0.0

**Comment by Kevin7720** [comment]
Thank you for sharing the download link. I'll download the model weights from the repository.
