### ISSUE TITLE
Confusing sample commands

### ISSUE THREAD

**Issue by cctsai831** [JeremyCJM/CCST#7]
```
## PACS, Overall, K=3
python data_list_generator.py --dataset PACS --target art_painting --mode overall --style adain --K 3 &
python data_list_generator.py --dataset PACS --target cartoon --mode overall --style adain --K 3 &
python data_list_generator.py --dataset PACS --target photo --mode overall --style adain --K 3 &
python data_list_generator.py --dataset PACS --target sketch --mode overall --style adain --K 3 &
```
As shown above, if I run the command, there would not exist a really 'target' domain, which is defined following the leave-one-domain-out setting. 

Therefore, should I remove all ```&``` and choose the one our own experiment needs the most???

**Comment by JeremyCJM** [comment]
Yes, of course you can! You only need to run four lines for leave-one-domain-out  evaluation purpose.
